GET http://localhost:5000/users

###

### Account Registration
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}


### Login user (good)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Login user (bad)
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "wrongpassword"
}

### Account Registration 2
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com",
  "password": "password456"
}